### ISSUE TITLE
Should we ship this? 

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-app#1]
This is ready for pre-1.0.0 review. cc: @AmpersandJS/core-team @AmpersandJS/community-leaders

**Comment by latentflip** [comment]
I think so. It's minimal but provides opportunity for extension. People in gitter have been getting on well with it. so I'd say it's good enough for a 1.0

**Comment by fyockm** [comment]
LGTM. Aside from the 2 small things I commented on the README in https://github.com/AmpersandJS/ampersand-app/commit/6af4c9352e6df8a06fb4d8152bb564de2388b429, I think it's ready. I like the pattern and think it will be beneficial in my own app.

Once this is published, we should update the [AmpersandJS/ampersand](https://github.com/AmpersandJS/ampersand) to utilize it.

**Comment by fyockm** [comment]
README updated.

:+1: from me now.

**Comment by latentflip** [comment]
Some readme thoughts:
- should we explain that this should probably never be required in modules, only at the application level.
- should we have an example of how to use it with modules that want to register with the app's app, ie some way to pass the app to the module on an init.

Doesn't necessarily have to be done pre release but I think guiding people on good/bad patterns will be helpful. As while not a global "variable" this is still a global in some sense.

**Comment by HenrikJoreteg** [comment]
@latentflip good thoughts. I think point one should be in the readme. Might also be good to write a full "/learn" page on some of the finer points like item two.

**Comment by ferdinandsalis** [comment]
@latentflip can you clarify your first point? :smile:

**Comment by latentflip** [comment]
@ferdinandsalis yes, sorry, my point was probably confused by the difference between commonjs modules (as in files within your application) and npm modules.

If you are creating a module, that you may wish to publish as a separate module to npm, to reuse in applications, it should probably not list ampersand-app as a dependency. This is basically a singleton and a global across your application, and submodules should probably not be introducing that kind of global into your environment just because you use them.

A silly example: if you want to make an npm module that will raise an alert on the "alert" event on the application, it would be better to make your module look something like this:

``` js
//good
//the alert-thing module
module.exports.initialize = function (app) {
  app.on('alert', function () { console.log('Alerted!') });
};

//in your application
var app = require('ampersand-app');
var alertThing = require('alert-thing');
alertThing.initialize(app);
```

than to have both the submodules and application trying to require ampersand-app

``` js
//bad
//the alert-thing module
var app = require('ampersand-app');
app.on('alert', function () { console.log('Alerted!'); });

//in the application
var app = require('ampersand-app');
require('alert-thing');
```

Hope that makes some sense!

**Comment by ferdinandsalis** [comment]
@latentflip yes it does. Thank you!

**Comment by HenrikJoreteg** [comment]
I think we're close enough here, that I'm going to pull the trigger and publish a `1.0.0` to npm. However, to minimize confusion, I think we should wait until the cli app have been updated to use it before we list it on the docs site and really encourage people to use it. 

I'd also like to get the travis and sauce labs stuff wired up for this (cc: @bear) as mentioned here: https://trello.com/c/qVjePXvC/21-ampersand-app-pattern-https-github-com-ampersandjs-ampersand-app

But anyway, this is semver, after all. The only thing that publishing a `1.0.0` means is that we're committing to following semver rules for the API from this point, and I think `extend` and `reset` seem simple/easy enough. Plus, getting a `1.0.0` published will make it easier for more of us to start implementing this pattern in our apps.

**Comment by HenrikJoreteg** [comment]
Thanks for the feedback, everyone `1.0.0` published to npm.

Also opened these related issues: #2, #4, #3
