### ISSUE TITLE
Configure travis/sauce setup for this

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-app#2]
Please document this so other folks can do this as well, going forward.

**Comment by bear** [comment]
where? is there a repo that I should add a README? or does one of the repos have a wiki?

**Comment by HenrikJoreteg** [comment]
Good question, maybe wiki on /ampersand??

**Comment by bear** [comment]
yea, I was thinking that also - would allow us to document other publishing scripts and meta org requirements

**Comment by bear** [comment]
travis is configured and the steps are documented in https://github.com/AmpersandJS/ampersand/wiki/Travis-CI
