### ISSUE TITLE
Include this in main ampersand.js.com/docs page when CLI has been updated

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-app#4]

**Comment by fyockm** [comment]
Is someone already working on updating the CLI example app? If not, would you like me to do so and submit a PR for it?

**Comment by HenrikJoreteg** [comment]
@fyockm that'd be great!

**Comment by fyockm** [comment]
Cool. I put it on my todo list. Should have something for review tomorrow.

**Comment by fyockm** [comment]
PR submitted for the CLI

**Comment by HenrikJoreteg** [comment]
awesome, thanks @fyockm. i think i'm just going to close this issue as it isn't really pertinent to ampersand-app as much as it is the cli and the site.
